# Generated by Django 4.1.2 on 2022-11-08 00:33

import datetime
from django.db import migrations, models
from appFamilia.models import *


class Migration(migrations.Migration):

    dependencies = [
        ('appFamilia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='fechanac',
            field=models.DateField(default=datetime.datetime(2022, 11, 7, 21, 33, 17, 987334)),
        ),
    
        

    ]
